"""Publish a self-contained local video library, transcripts and coverage evidence."""
import json,pathlib,html
ROOT=pathlib.Path(__file__).resolve().parents[2];RUN=ROOT/'output/playwright/workflow-videos-2026-09-26'
plan=json.loads((RUN/'storyboard.json').read_text());manifest={v['id']:v for v in json.loads((RUN/'video-manifest.json').read_text())} if (RUN/'video-manifest.json').exists() else {}
e=html.escape
cards=[];md=['# Fervid Budget workflow training','', 'Real application recordings with synthetic demonstration records. Narration: Google Gemini 3.8 Flash TTS, Kore, via OpenRouter.','', 'Each lesson documents a worked example, the feature it demonstrates, and its practical limits. Captions are aligned by narrated scene and phrase; they are not word-level transcription.','']
for v in plan['videos']:
 m=manifest.get(v['id']);secs=m['duration'] if m else 0
 transcript='\n\n'.join(s['title']+'\n'+s['narration'] for s in v['scenes'])
 (RUN/'videos').mkdir(exist_ok=True);(RUN/'videos'/f'{v["id"]}.txt').write_text(v['title']+'\n'+transcript+'\n')
 md += ['## '+v['title'],'', '**Audience:** '+v['audience'],'', '**Demonstrated features:** '+ '; '.join(v['features']), '', '**Limitations:** '+ '; '.join(v['limitations']),'']
 chapters=[]
 for i,s in enumerate(v['scenes']):
  c=next((c for c in (m or {}).get('chapters',[]) if c['scene']==s['id']),None)
  start=c['start'] if c else 0
  chapters.append(f'<details><summary><button class="seek" data-time="{start:.3f}">{i+1:02} · {e(s["title"])}</button></summary><p>{e(s["narration"])}</p><a href="{e(s["screenshot"])}" target="_blank">View captured outcome</a></details>')
  md += [f'### {i+1}. {s["title"]}', '',s['narration'],'',f'Evidence: [{s["id"]}]({s["screenshot"]})','']
 video=f'<video controls preload="none" poster="{e(v["scenes"][0]["screenshot"])}"><source src="{e(m["file"])}" type="video/mp4"></video>' if m else '<p class="pending">Rendering in progress</p>'
 links=f'<a href="videos/{v["id"]}.mp4" download>MP4</a> <a href="videos/{v["id"]}.srt" download>Captions</a> <a href="videos/{v["id"]}.txt" download>Transcript</a>'
 cards.append(f'<article data-search="{e(v["title"]+" "+v["audience"]+" "+" ".join(v["features"])).lower()}"><div class="eyebrow">{e(v["audience"])} · {int(secs)//60}:{int(secs)%60:02} · {len(v["scenes"])} chapters</div><h2>{e(v["title"])}</h2>{video}<div class="downloads">{links}</div><h3>What you will learn</h3><ul>'+''.join('<li>'+e(f)+'</li>' for f in v['features'])+'</ul><h3>Limits to understand</h3><ul>'+''.join('<li>'+e(f)+'</li>' for f in v['limitations'])+'</ul><div class="chapters">'+''.join(chapters)+'</div></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fervid Budget — Workflow Library</title><style>
:root{--paper:#f4f0e9;--ink:#25221e;--accent:#a8381b}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,sans-serif}header{max-width:1250px;margin:auto;padding:60px 28px 24px}h1{font-size:clamp(34px,5vw,64px);line-height:1.08;letter-spacing:-2px;margin:14px 0 24px}header p{max-width:860px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#745e51}a{color:var(--accent)}.controls{position:sticky;top:0;z-index:3;background:var(--paper);padding:16px 28px;border-block:1px solid #d5cabc}.controls>div{max-width:1194px;margin:auto;display:flex;gap:24px;align-items:center;flex-wrap:wrap}input{font:inherit;padding:12px 16px;border:1px solid #bba99b;border-radius:8px;min-width:min(100%,360px)}main{max-width:1250px;padding:28px;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,480px),1fr));gap:28px;margin:auto}article{background:white;border:1px solid #ddd2c5;border-radius:16px;padding:24px;overflow:hidden}h2{font-size:26px;line-height:1.2;margin:12px 0 20px}h3{font-size:16px;margin-bottom:8px}video{width:100%;background:#25221e;aspect-ratio:16/9;border-radius:8px}ul{padding-left:22px;margin-top:0}.downloads{display:flex;gap:20px;font-size:14px;padding:12px 0}.chapters{border-top:1px solid #ddd2c5;margin-top:20px}details{border-bottom:1px solid #e5ddd4;padding:10px 0}summary{cursor:pointer}button.seek{border:0;background:none;text-align:left;color:var(--ink);font:600 14px/1.5 system-ui;cursor:pointer}details p{font-size:14px}details a{font-size:13px}footer{max-width:1194px;margin:30px auto;padding:28px;font-size:14px;border-top:1px solid #ccbdae}.hidden{display:none}a:focus-visible,button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #a8381b;outline-offset:4px}
</style><header><div class="eyebrow">Fervid Budget / Recorded workflow training</div><h1>See the workflow.<br>Understand the limits.</h1><p>Detailed demonstrations for requesters, managers, Accounts, and administrators. Follow real entries from creation through decisions, payment records, recoveries, reporting, and controls.</p><p><strong>Demonstration environment:</strong> all names and financial examples are synthetic. Recording a payment does not transfer money. The application build and evidence are included with this library.</p></header><div class="controls"><div><input id="search" aria-label="Search lessons" placeholder="Search a feature or role…"><span id="count"></span><a href="coverage-and-transcripts.md">Full coverage & transcripts</a><a href="verification.json">Verification</a></div></div><main>'''+''.join(cards)+'''</main><footer>Playwright recordings with animated cursor and field highlights. Remotion titles and screen frames. Gemini 3.8 Flash TTS narration through OpenRouter. Local FFmpeg composition. <a href="reference/sources.md">Technology sources</a>. The videos demonstrate the captured application version; they do not certify future changes, tax treatment, or restoration of backups.</footer><script>
const articles=[...document.querySelectorAll('article')],search=document.querySelector('#search'),count=document.querySelector('#count');function filter(){let n=0;for(const a of articles){const yes=a.dataset.search.includes(search.value.toLowerCase());a.classList.toggle('hidden',!yes);if(yes)n++;}count.textContent=n+' lessons';}search.addEventListener('input',filter);filter();document.querySelectorAll('.seek').forEach(b=>b.addEventListener('click',()=>{const v=b.closest('article').querySelector('video');if(v){const seek=()=>{v.currentTime=Number(b.dataset.time);v.play().catch(()=>{});};if(v.readyState===0){v.addEventListener('loadedmetadata',seek,{once:true});v.load();}else seek();}}));document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause();})));
</script></html>'''
(RUN/'index.html').write_text(page);(RUN/'coverage-and-transcripts.md').write_text('\n'.join(md))
print(f'Library built: {len(cards)} lessons, {len(manifest)} playable videos')
