import React from 'react';
import {AbsoluteFill,Composition,registerRoot,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
const ink='#25221e',accent='#a8381b',paper='#f4f0e9';
const Intro=({title='Fervid Budget',audience='Workflow training',index='01',kind='intro'})=>{
 const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();const opacity=interpolate(f,[0,12,durationInFrames-12,durationInFrames-1],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
 return <AbsoluteFill style={{backgroundColor:paper,color:ink,fontFamily:'Arial, sans-serif',padding:140,justifyContent:'center'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:22,background:accent}}/><div style={{opacity,transform:`translateY(${interpolate(f,[0,20],[24,0],{extrapolateRight:'clamp'})}px)`}}><div style={{fontSize:26,letterSpacing:6,textTransform:'uppercase',color:accent,fontWeight:700}}>Fervid Budget · {kind==='outro'?'Workflow complete':'Practical training'}</div><div style={{display:'flex',alignItems:'center',gap:35,marginTop:60}}><span style={{fontSize:110,color:accent,fontWeight:700}}>{index}</span><h1 style={{fontSize:80,lineHeight:1.08,margin:0,maxWidth:1400}}>{title}</h1></div><p style={{fontSize:34,color:'#665c51',marginTop:50}}>{audience}</p><p style={{fontSize:25,color:'#796e62',marginTop:60}}>Recorded in the real application · Synthetic demonstration data</p></div></AbsoluteFill>
}
const Frame=({title='Workflow',sceneTitle='Step',step='01 / 04',audience='Admin'})=><AbsoluteFill style={{backgroundColor:'transparent',fontFamily:'Arial, sans-serif',color:ink}}><div style={{position:'absolute',inset:0,background:paper}}/><div style={{position:'absolute',top:90,left:160,width:1600,height:900,background:'#000'}}/><div style={{position:'absolute',left:46,top:21,width:1010,display:'flex',alignItems:'center',gap:18}}><div style={{width:48,height:48,borderRadius:12,background:accent,color:'white',font:'bold 32px Georgia',display:'grid',placeItems:'center'}}>F</div><div><div style={{fontSize:15,fontWeight:700,color:accent,letterSpacing:2}}>FERVID BUDGET · {audience.toUpperCase()}</div><div style={{fontSize:26,fontWeight:700,marginTop:2,maxWidth:950,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{title}</div></div></div><div style={{position:'absolute',right:46,top:20,width:730,height:62,display:'flex',alignItems:'center',justifyContent:'flex-end',textAlign:'right',fontSize:23,lineHeight:1.2,color:'#675d52'}}>{step} · {sceneTitle}</div><div style={{position:'absolute',bottom:18,left:160,right:160,height:62,borderRadius:12,background:'#25221e'}}/><div style={{position:'absolute',bottom:1,left:160,fontSize:12,color:'#786e62'}}>Demo data · Recording entries does not transfer money</div></AbsoluteFill>;
function Root(){return <><Composition id="Title" component={Intro} width={1920} height={1080} fps={30} durationInFrames={90}/><Composition id="Frame" component={Frame} width={1920} height={1080} fps={30} durationInFrames={1}/></>}
registerRoot(Root);
