from capture import *
V='10-accounts-ownership'
with scene(V,'06-handoff','Return the reservation to Accounts','Confirm that no bank payment has been initiated, then release the reservation with a brief reason. The request returns to Approved, awaiting payment, and another Accounts user can pick it up. This releases the processing assignment; it does not create a payment, remove the approval, or cancel the request. Resume only after the handoff is clear.', 'Payment queue'):
 check('radio','Release it Back to Approved — awaiting payment. Anyone in Accounts can pick it up.');fill('Reason','Demonstration handoff: payment proof is ready, release before the next operator records it.');check('checkbox','I confirm no payment has been initiated for this request');click('button','Release reservation')
goto('/requests/13')
V='19-payment-evidence'
video(V,'Payment evidence and the immutable request trail','Accounts and reviewers',['Attach payment proof at confirmation','Read payment and request history','Understand correction limitations'],['New payment entry begins with an approved request.','A request-linked payment cannot be edited or cancelled in the ordinary interface.','Stored proof is a document; it does not independently verify a bank transfer.'])
with scene(V,'01-record','Start from an approved vendor invoice','This example pays Lesson Studio Office Supplies against its approved two thousand five hundred rupee invoice request. Payment entry starts from an approved request, carrying its vendor and classification forward. Record the amount, mode, and unique reference, then move to confirmation. This connects the invoice request, approval, payment, and vendor context in one traceable workflow.'):
 click('button','Record payment');fill('Amount actually paid','2500');select('Payment mode','NEFT');fill('Transaction / UTR reference','DEMO-P-EVIDENCE-2500');click('button','Payment settled →')
with scene(V,'02-proof','Attach proof at the confirmation step','Attach the bank advice at confirmation, where the document is uploaded once when you save. This training file is clearly marked synthetic. In live work, use the actual payment evidence and verify that the payee, amount, date, and reference agree. An uploaded document supports review; Fervid does not independently validate the transfer with your bank.'):
 snapshot();call('click','text=Attach the bank advice');call('upload',RUN/'evidence/demo-payment-advice.pdf');click('button','Confirm and save payment')
print([(x.get('role'),x.get('name'),x.get('url')) for x in snapshot('evidence-saved') if x.get('role') in ['link','button','heading']])
