from capture import *
V='14-manager-shortfall'
video(V,'Resolve shortfalls, concerns and writeoffs','Managers and Accounts',['Send a shortfall for manager review','Keep balance payable','Accept an explicit writeoff','Raise and answer a concern'],['A concern does not reverse the payment.','Only the assigned manager makes the partial settlement decision.','Accept and close prevents paying the written-off balance against this request.'])
with scene(V,'01-review-needed','Ask the manager to decide the shortfall','When Accounts cannot treat the lower payment as an ordinary installment or a fully discharged obligation, send the difference for manager review. Here eight thousand was paid against twelve thousand approved. Enter the reason and explicitly choose the manager review outcome. Further payment waits while the assigned approver decides what should happen to the four thousand rupee balance.'):
 goto('/requests/7');click('button','Record payment');fill('Amount actually paid','8000');select('Payment mode','NEFT');fill('Transaction / UTR reference','DEMO-P-REVIEW-KEEP');click('button','Payment settled →');check('radio','Ask manager to accept a shortfall Pause further payment while the approver decides whether to write off the remaining balance. Manager review');fill('Reason for any deduction or shortfall','Manager to decide whether INR 4000 remains payable after supplier discussion.');click('button','Confirm and save payment')
# Independent examples for the alternative manager decisions, entered in the same real UI.
for request_id,reference in [(8,'DEMO-P-REVIEW-WRITEOFF'),(9,'DEMO-P-REVIEW-CONCERN')]:
 goto(f'/requests/{request_id}');click('button','Record payment');fill('Amount actually paid','8000');select('Payment mode','NEFT');fill('Transaction / UTR reference',reference);click('button','Payment settled →');check('radio','Ask manager to accept a shortfall Pause further payment while the approver decides whether to write off the remaining balance. Manager review');fill('Reason for any deduction or shortfall','Manager review requested for the remaining INR 4000.');click('button','Confirm and save payment')
login('mira@demo.fervid.local','DemoPass2026!');goto('/requests/7/partial-review');snapshot('manager-options')
with scene(V,'02-keep','Keep the balance on the original approval','The first option is to pay the balance later. Mira records a payment plan and keeps four thousand rupees payable. The existing approval remains the authority for the next installment, so the requester does not need to create a duplicate request. This is the appropriate branch when the organisation still owes the balance.'):
 fill('Payment plan or reason','Remaining INR 4000 is still owed; pay after final delivery confirmation.');click('button','Keep balance payable')
goto('/requests/8/partial-review')
with scene(V,'03-writeoff','Accept an explicit writeoff','For a separate example, the manager decides the remaining four thousand is no longer owed. Accept and close displays the approved amount, total paid, and amount written off before confirmation. Read this comparison carefully. Closing as partial accepted is a final settlement decision, not merely permission to pay the remaining amount next month.'):
 click('button','Accept and close');fill('Note','Demonstration negotiated final settlement: remaining INR 4000 is no longer owed.');click('button','Accept and close',nth=1)
goto('/requests/9/partial-review')
with scene(V,'04-concern','Raise a concern without reversing cash','In the third example the manager needs an explanation. Raise a concern records the question and keeps the request under discussion. The interface explicitly warns that this does not reverse anything: the eight thousand rupee payment remains recorded. Accounts must answer the concern so the manager can make a supported decision about the outstanding balance.'):
 click('button','Raise a concern');fill('What is wrong','Please confirm why INR 4000 was withheld and whether it remains owed.');click('button','Raise concern')
login('anil@demo.fervid.local','DemoPass2026!');goto('/requests/9/partial-review')
print([(x.get('role'),x.get('name')) for x in snapshot('concern-answer') if x.get('role') in ['textbox','button']])
