from capture import *
fill('Short title','Lesson E recovery walkthrough advance');fill('Expected return date','2026-10-15');fill('Repayment or refund terms','Return unused field visit funds in two instalments.');fill('Amount','7000');fill('What the money is for','Field visit travel advance for recovery demonstration');fill('Purpose','Demonstrate validation and complete return history');select('Approver','2');click('button','Submit request')
path=next(n['url'] for n in snapshot() if n.get('role')=='link' and n.get('name')=='View this request');rid=path.split('/')[-1];(RUN/'recapture-request-id.txt').write_text(rid)
login('mira@demo.fervid.local','DemoPass2026!');goto(path);click('button','Approve ₹7,000.00');click('button','Approve request');login('anil@demo.fervid.local','DemoPass2026!');goto(path);click('button','Record payment');select('Payment mode','upi');fill('Transaction / UTR reference','LESSON-E-RECAPTURE-7000');click('button','Payment settled →');click('button','Confirm and save payment');goto('/recoverables/'+rid)
d=plan();v=next(v for v in d['videos'] if v['id']=='16-recovery-returns');(RUN/'video16-previous-storyboard.json').write_text(json.dumps(v,indent=2));v['scenes']=[];save(d)
with scene('16-recovery-returns','01-balance','Payout completion is not recovery completion','This advance has been paid out, yet seven thousand rupees remains outstanding. The recoverable detail separates total paid, returned or reconciled, and the balance still due. The latest payment is historical evidence of cash leaving the company. It is not the current balance. Recoverable payments are explicitly marked as excluded from budget actuals.',expected='Outstanding balance'):
 goto('/recoverables/'+rid);click('heading','Recoverable details')
with scene('16-recovery-returns','02-partial','Record the first return','The employee returns two thousand rupees. Choose Money returned, enter the amount and actual recovery date, then provide the bank reference and evidence location. Each entry is permanent, so verify the source record before confirming. The return reduces the outstanding balance to five thousand rupees while preserving the original seven thousand rupee payout.',expected='₹5,000.00'):
 select('Recovery type','return');fill('Amount received or reconciled (₹)','2000');fill('Bank / accounting reference','LESSON-E-RETURN-2000');fill('Evidence and explanation','Unused advance returned by Riya. Demonstration bank receipt E-2000 retained in training records.');click('button','Record recovery');call('dialog-accept');click('heading','Recoverable details')
with scene('16-recovery-returns','03-overbalance','Reject a recovery above the balance','An accidental six thousand rupee entry would exceed the five thousand rupees remaining. The application rejects it and keeps the entered explanation so Accounts can correct the amount. No extra recovery is saved. This protection helps prevent a negative balance, but it does not replace checking the underlying bank or accounting evidence.',expected='Recovery was not saved'):
 select('Recovery type','return');fill('Amount received or reconciled (₹)','6000');fill('Bank / accounting reference','LESSON-E-FINAL-RETURN');fill('Evidence and explanation','Final unused advance return. Correct bank amount is five thousand rupees.');click('button','Record recovery');call('dialog-accept');snapshot();call('run-code',"async page => { const error=page.locator('#recovery-error'); await error.scrollIntoViewIfNeeded(); await page.evaluate(()=>document.getElementById('recovery-error').scrollIntoView({block:'start'})); }");time.sleep(.5)
with scene('16-recovery-returns','04-close','Complete recovery and retain the history','We correct the amount to five thousand rupees and confirm the final return. The outstanding balance becomes zero and the record is fully reconciled. Both dated returns remain in the recovery history. The original payout stays seven thousand rupees, giving a clear trail from payment to complete recovery without overwriting the transaction.',expected='Fully reconciled'):
 fill('Amount received or reconciled (₹)','5000');click('button','Record recovery');call('dialog-accept');click('heading','Recovery history');snapshot();call('run-code',"async page => { await page.getByRole('heading',{name:'Recovery history',exact:true}).evaluate(el=>el.scrollIntoView({block:'start'})); }")
print('RECOVERY RECAPTURE COMPLETE request '+rid,flush=True)
