from capture import *
video('23-notifications-access-recovery','Manage notifications and restore sign-in access','All users and administrators',['Read personal notifications','Filter unread activity','Review event audiences and email setup','Catch template mistakes before saving','Offline access recovery through administrator','Reset a dedicated demonstration account'],['In-app notifications are always enabled; email is separate and opt-in per event.','Email reset needs configured delivery; this demonstration installation has no SMTP.','Administrator identity verification and private password delivery happen outside the application.'])
with scene('23-notifications-access-recovery','01-personal','Find activity that needs attention','Notifications brings together activity relevant to the signed-in user. All and Unread show different views of the same personal inbox; Mentions and Reminders narrow the type of activity. Open an item to return to its related record. Reading a notification does not approve, pay, or resolve the request itself.', 'Notifications'):
 goto('/notifications');click('link','Unread',exact=False)
with scene('23-notifications-access-recovery','02-read','Clear read status, then return to the workflow','Mark all read clears the unread marker for this user. It does not change request status or another person’s inbox. Use unread activity as a prompt to investigate, then perform the required action on the actual request or payment. A cleared inbox is therefore not proof that every financial workflow has been completed.', 'Everything here is read'):
 click('button','Mark all read');click('link','All',exact=False)
with scene('23-notifications-access-recovery','03-email','Separate in-app activity from email delivery','Notification rules define event audiences and optional email delivery. In-app activity always fires. Email requires SMTP settings and an enabled rule for the event. The SMTP password comes from the server environment and has no form field here. This local installation has no email service, so the lesson does not claim that an email has been delivered.', 'In-app notifications always fire'):
 goto('/admin/notifications');click('textbox','SMTP host');call('mousewheel','0','430')
with scene('23-notifications-access-recovery','04-invalid-template','Catch an unsupported template field','Edit an event to inspect who receives it and which fields can appear in its message. Here we deliberately type an unsupported field into the subject. Saving rejects the mistake and keeps the draft available for correction. Use only the listed template fields; a field name that looks plausible is not automatically supported.', 'That did not save'):
 click('button','Edit',nth=0);fill('Subject','Training {{UnsupportedField}}');click('button','Save rule')
with scene('23-notifications-access-recovery','05-discard','Discard the experiment without changing a live rule','The rejected draft remains visible so the administrator can correct it. For this training experiment, Cancel closes the editor and leaves the stored rule unchanged. In a real change, correct the field, review the audience and email setting, and save intentionally. Editing a notification rule affects future delivery; it does not resolve an existing request.', 'Notification rules'):
 click('button','Cancel')
with scene('23-notifications-access-recovery','06-help','Use the sign-in recovery path that is available','The sign-in help page tells users whether email password reset is available. Here it is not enabled, so the page points to the administrator. The user should provide their account email and describe the problem, never send their password. Where email reset is configured, the application offers a one-time link that expires after thirty minutes.', 'Email password reset is not enabled'):
 goto('/login/help')
login();goto('/users');click('button','＋ Add user');fill('Email','tara@demo.fervid.local');fill('Name','Tara Training');check('checkbox','Requester — Raise and manage your own payment requests.');fill('Password','TrainingOld2026!');click('button','Add User')
# Ground the row selector in the fresh user-list snapshot; user name is unique.
snapshot('tara-created');call('run-code',"async page => { await page.getByRole('row').filter({hasText:'tara@demo.fervid.local'}).getByRole('button',{name:'Edit',exact:true}).click(); }")
with scene('23-notifications-access-recovery','07-admin-reset','Reset a separate demonstration account','After verifying the person’s identity outside the application, an administrator opens Users and edits the correct account. Reset password is separate from the role checkboxes and Active status. We replace the password only for Tara, a dedicated training account. Deliver a replacement privately and confirm the account is active; do not use shared credentials for recovery.', 'Tara Training'):
 fill('Reset password','TrainingNew2026!');click('button','Save user')
with scene('23-notifications-access-recovery','08-verify-login','Verify access with the replacement password','A reset is useful only if the person can sign in afterward. We open the login form, enter Tara’s email and the replacement demonstration password, and verify that her own home screen loads. The available navigation follows her roles. Successful sign-in confirms access; it does not grant administrative privileges or change the account’s financial responsibilities.', 'Tara Training'):
 login('tara@demo.fervid.local','TrainingNew2026!')
login()
