from capture import *
with scene('25-month-close','02-lock','Read the close indicators, then lock','The Month Close panel counts unpaid budgeted heads, unbudgeted spending, and overspending across the full month. Heads with no budget or activity are excluded from unpaid counts. Our blank month has no activity. Enter a meaningful reason and confirm the lock. The confirmation makes clear that budgets and payments become read-only.', 'Unlock Month'):
 fill('Lock reason','Training: November plan reviewed; no activity recorded.');click('button','Lock Month');call('dialog-accept')
with scene('25-month-close','03-verify','Verify the read-only budget state','Now open the same month in Budgets. The Locked label and explanation remain visible, and budget inputs and Save Budgets are disabled. This is the practical effect of closing the period. Locking does not validate invoices, match bank statements, or certify accounting completeness; those reviews must be performed before the period is closed.', 'This month is locked'):
 goto('/budgets?month=2026-11');call('mousewheel','0','340')
with scene('25-month-close','04-unlock','Reopen only with a documented reason','If a legitimate correction is needed, return to the grid and enter an unlock reason. Confirming reopens the period for budget and payment changes. In this demonstration we reopen November for further training. Keep the reason specific enough that another reviewer can understand why the closed period was changed.', 'Lock Month'):
 goto('/grid?month=2026-11');fill('Unlock reason','Training completed: reopen November for authorised planning corrections.');click('button','Unlock Month');call('dialog-accept')
with scene('25-month-close','05-audit','Trace the lock and unlock decisions','The Audit Log provides the evidence trail. Filter to the month entity to isolate period control activity. The lock and unlock entries identify the actor, time, action, and reason. This history supports review, but the existence of an audit entry does not replace checking that the underlying correction was appropriate.', 'Training completed'):
 goto('/audit');select('Entity','Month Lock');click('button','Filter')
