from capture import *
video('27-role-capabilities-scopes','Build a limited role and verify the resulting access','Administrators and access reviewers',['Create custom role with no initial permissions','Separate action capabilities from record scope','Inspect advanced permissions','Assign only to a demonstration user','Verify actual restricted access'],['Changing a role affects every user assigned to it.','A role name alone does not define access; capabilities and record scopes do.','Multiple roles can broaden access; review the complete membership set.'])
with scene('27-role-capabilities-scopes','01-new-role','Start a custom role with no permissions','Roles and permissions separates what a person may do from which records they can see. Creating a new role starts with no permissions. We create an own-request viewer for training and leave the standard team roles unchanged. Choose a descriptive name, but remember that the name is only a label; the permission matrix defines access.', 'Training own request viewer'):
 click('button','＋ New role');fill('Role name','Training own request viewer',nth=1);fill('Description','Training only: read own payment requests, without creating or approving.',nth=1);click('button','Create role')
with scene('27-role-capabilities-scopes','02-grants','Give view capability and Own scope','For Payment requests, enable View and select Own under Records it can see. View determines the action, while Own restricts the record set. We leave Create, Edit, Approve, and Cancel unselected. Save role persists this combination. Setting All would broaden the visible set; a limited viewer should receive only the scope needed for their responsibility.', 'Training own request viewer'):
 call('check',ref('checkbox','View',nth=0));call('check',ref('radio','Own',nth=0));click('button','Save role');click('textbox','Role name')
with scene('27-role-capabilities-scopes','03-advanced','Inspect the permissions behind a matrix cell','The advanced section exposes the individual permissions behind each row. Use it when a broad matrix label needs closer review. The user count and change notice matter: saving an established role affects all users holding it. This training role has no users yet, so we can inspect the grant before assigning it to one demonstration account.', 'Advanced'):
 click('generic','Advanced — every permission behind this row',nth=0)
goto('/users');snapshot('tara-before-role');call('run-code',"async page => { await page.getByRole('row').filter({hasText:'tara@demo.fervid.local'}).getByRole('button',{name:'Edit',exact:true}).click(); }")
with scene('27-role-capabilities-scopes','04-membership','Assign the role and remove the broader membership','In Users, assign the custom viewer role to Tara and remove her previous Requester membership. Keeping an additional role can broaden access, so review the whole set of checkboxes rather than only the new one. This change applies solely to our training account; the manager, accounts, and requester identities used elsewhere remain unchanged.', 'Tara Training'):
 call('uncheck',ref('checkbox','Requester — Raise and manage your own payment requests.'));check('checkbox','Training own request viewer — Training only: read own payment requests, without creating or approving.');click('button','Save user')
with scene('27-role-capabilities-scopes','05-verify','Verify the experience from the restricted account','Sign in as Tara to check the outcome from the user’s perspective. Her navigation is reduced to the areas allowed by the custom role. My requests is available for viewing, but creating or approving requests is not part of this role. Testing as the affected user is essential because an administrator’s screen does not represent restricted access.', 'My requests'):
 login('tara@demo.fervid.local','TrainingNew2026!');click('link','▤ My requests')
login()
