from capture import *
video('17-recovery-reconciliation','Reconcile expenses and authorised adjustments','Accounts',['Expense reconciliation','Documented adjustment','Evidence trail'],['Entries reduce the recoverable only','No automatic budget expense or tax posting'])
with scene('17-recovery-reconciliation','01-distinction','Choose the right recovery event','The venue deposit has now been paid and five thousand rupees is outstanding. Recovery has three meanings here: money returned, an expense reconciled against supported spending, or a documented balance adjustment. These are different real world events, even though each reduces the balance. Choose the event that matches the evidence rather than using a return for every reduction.'):
 goto('/recoverables/11');select('Recovery type','expense')
with scene('17-recovery-reconciliation','02-expense','Reference an approved expense','The venue retains fifteen hundred rupees for approved cleaning charges. Accounts records an expense reconciliation and references the approved invoice and accounting record. This reduces the deposit balance to three thousand five hundred rupees. It does not automatically charge a budget head or create the expense posting elsewhere; the separate accounting treatment still needs to be completed.'):
 fill('Amount received or reconciled (₹)','1500');fill('Bank / accounting reference','LESSON-E-CLEANING-INVOICE');fill('Evidence and explanation','Approved venue cleaning invoice E-CLEAN-1500. Expense treatment recorded separately in the accounting records; this entry reconciles the deposit only.');click('button','Record recovery');call('dialog-accept')
with scene('17-recovery-reconciliation','03-adjustment','Explain who authorised an adjustment','An additional five hundred rupees is written down under a documented settlement approved by the manager. We select Balance adjustment, identify the approval reference, and explain who authorised it and why. An adjustment is not cash received. The entry reduces the outstanding balance to three thousand rupees and remains visible with its recorder and date.'):
 select('Recovery type','adjustment');fill('Amount received or reconciled (₹)','500');fill('Bank / accounting reference','LESSON-E-MIRA-APPROVAL');fill('Evidence and explanation','Mira Shah authorised a five hundred rupee venue settlement adjustment in demonstration approval E-SETTLEMENT. No cash was returned for this adjustment.');click('button','Record recovery');call('dialog-accept')
with scene('17-recovery-reconciliation','04-trail','Read the remaining exposure','The deposit history now distinguishes fifteen hundred rupees of expense reconciliation from a five hundred rupee adjustment. Three thousand rupees remains outstanding and must still be followed up. The original five thousand rupee payment has not changed. Keep supporting evidence outside this explanatory note and use the request conversation for follow up context.',expected='₹3,000.00'):
 goto('/recoverables/11');click('link','⤓ Export this record')
