from capture import *
video('24-configuration-audit-backups','Configure controls, inspect history, and create a backup','Administrators and installation operators',['Request numbering and document policy','Urgency, approval and reminder controls','Recoverable category lifecycle','Audit filters','Create backup and read recovery guidance'],['Second approval above a threshold is a future feature.','In-use recoverable categories cannot be deleted.','Backup creation does not verify a restore. Configuration and secrets need separate operational management.'])
with scene('24-configuration-audit-backups','01-policy','Understand request and approval controls','Configuration controls request numbering, supporting documents, urgency, and approver choice. Requiring a document still allows a written exception reason when the document is unavailable. Urgency follows the same approval rules. Self-approval is always blocked, while second approval above a threshold is explicitly reserved for a future version. Review these policies with your organisation before changing them.', 'Second approval above a threshold'):
 goto('/configuration');click('textbox','Prefix');call('mousewheel','0','390')
with scene('24-configuration-audit-backups','02-reminders','Read payment and reminder limitations','Payment modes determine the options offered when recording a payment; they do not connect the application to a bank. Every new payment starts from an approved request. Reminder thresholds are measured in days, not working hours. A request placed on hold is waiting on the requester and is excluded from reminders, so hold status needs active operational follow-up.', 'Reminders are counted in days'):
 click('textbox','Payment modes offered');call('mousewheel','0','360')
with scene('24-configuration-audit-backups','03-category','Add a recoverable category with specific requirements','Recoverable categories add structured requirements to the common recovery fields. Here we create a training retention category that requires both the related project and the counterparty company. Every recoverable still needs a reason, expected return date, and refund terms. Category rules describe what must be captured; they do not automatically recover money or post an expense.', 'Training retention'):
 fill('New category','Training retention');select('Must also capture','both');click('button','Add category');click('textbox','Name for Training retention')
with scene('24-configuration-audit-backups','04-category-update','Edit requirements and remove an unused category','A category can be edited in place, preserving its identity. We change the display name, save it, and then delete this unused training category. Check the In use count before retiring a real category. The application refuses deletion when requests already refer to it; deactivation is the way to stop future use while preserving history.', 'Recoverable categories'):
 fill('Name for Training retention','Training retention deposit');click('button','Save Training retention');click('button','Delete Training retention deposit')
with scene('24-configuration-audit-backups','05-audit','Filter category changes and inspect evidence','Audit filters narrow the record to a particular entity, action, actor, or date range. Here the Recoverable Category filter shows our category creation, update, and deletion. Expand Before and after to inspect recorded values where available. The audit trail identifies changes; reviewers still need to interpret whether each change matches an approved business decision.', 'Training retention'):
 goto('/audit');select('Entity','Recoverable Category');click('button','Filter');click('generic','Before / after')
with scene('24-configuration-audit-backups','06-backup','Create a server backup and understand readiness','Create Backup packages the database and payment and request attachments on the application server. The page then lists the backup and its readiness status. Files present is a useful check, but it is not evidence that a restore works. Configuration and external secrets are managed separately, so a complete recovery plan includes those operational dependencies.', 'Operator restore command'):
 goto('/backups');click('button','Create Backup')
with scene('24-configuration-audit-backups','07-recovery','Read the operator recovery procedure','Expand the operator restore command and review the recovery procedure. A real recovery should first be tested into a separate database and attachment directory, with totals, records, and downloads checked. Production restoration replaces newer changes and requires the application to be stopped. This lesson creates a backup; it does not claim that a restore test has been performed.', 'Restore safely with your operator'):
 click('generic','Operator restore command');call('mousewheel','0','380')
