from capture import *
video('16-recovery-returns','Recover an advance in stages','Accounts',['Read outstanding balance','Partial return','Overbalance protection','Full recovery'],['Entries are permanent','Original payouts remain unchanged'])
with scene('16-recovery-returns','01-balance','Payout completion is not recovery completion','This advance has been paid out, yet seven thousand rupees remains outstanding. The recoverable detail separates total paid, returned or reconciled, and the balance still due. The latest payment is historical evidence of cash leaving the company. It is not the current balance. Recoverable payments are explicitly marked as excluded from budget actuals.',expected='Outstanding balance'):
 goto('/recoverables/2')
with scene('16-recovery-returns','02-partial','Record the first return','The employee returns two thousand rupees. Choose Money returned, enter the amount and actual recovery date, then provide the bank reference and evidence location. Each entry is permanent, so verify the source record before confirming. The return reduces the outstanding balance to five thousand rupees while preserving the original seven thousand rupee payout.'):
 select('Recovery type','return');fill('Amount received or reconciled (₹)','2000');fill('Bank / accounting reference','LESSON-E-RETURN-2000');fill('Evidence and explanation','Unused advance returned by Riya. Demonstration bank receipt E-2000 retained in training records.');click('button','Record recovery');call('dialog-accept')
with scene('16-recovery-returns','03-overbalance','Reject a recovery above the balance','An accidental six thousand rupee entry would exceed the five thousand rupees remaining. The application rejects it and keeps the entered explanation so Accounts can correct the amount. No extra recovery is saved. This protection helps prevent a negative balance, but it does not replace checking the underlying bank or accounting evidence.',expected='Recovery was not saved'):
 select('Recovery type','return');fill('Amount received or reconciled (₹)','6000');fill('Bank / accounting reference','LESSON-E-FINAL-RETURN');fill('Evidence and explanation','Final unused advance return. Correct bank amount is five thousand rupees.');click('button','Record recovery');call('dialog-accept')
with scene('16-recovery-returns','04-close','Complete recovery and retain the history','We correct the amount to five thousand rupees and confirm the final return. The outstanding balance becomes zero and the record is fully reconciled. Both dated returns remain in the recovery history. The original payout stays seven thousand rupees, giving a clear trail from payment to complete recovery without overwriting the transaction.',expected='Fully reconciled'):
 fill('Amount received or reconciled (₹)','5000');click('button','Record recovery');call('dialog-accept')
