import path from 'node:path';import fs from 'node:fs/promises';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {bundle} from '@remotion/bundler';import {renderStill,renderMedia,selectComposition} from '@remotion/renderer';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'../..');const args=process.argv.slice(2);let directory;const selected=new Set();for(let i=0;i<args.length;i++){if(args[i]==='--video'){for(const v of args[++i].split(','))selected.add(v)}else if(!args[i].startsWith('--'))directory=args[i];else throw Error('Unknown option '+args[i]);}
const run=path.resolve(directory||path.join(root,'output/playwright/workflow-videos-2026-09-26'));const plan=JSON.parse(await fs.readFile(path.join(run,'storyboard.json'),'utf8'));const assets=path.join(run,'assets');await fs.mkdir(assets,{recursive:true});
const source=await fs.readFile(path.join(here,'Composition.tsx'),'utf8');const hash=(data)=>crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');
const valid=async(file,key)=>{try{return (await fs.stat(file)).size>0&&(await fs.readFile(file+'.sha256','utf8'))===key}catch{return false}};
const jobs=[];
for(const v of plan.videos){if(selected.size&&!selected.has(v.id))continue;const inputProps={title:v.title,audience:v.audience,index:v.id.slice(0,2)};const file=path.join(assets,v.id+'-intro.mp4');const key=hash([source,'title-v2',inputProps]);if(!await valid(file,key))jobs.push({id:'Title',inputProps,file,key});
 for(const [n,s] of v.scenes.entries()){const inputProps={title:v.title,audience:v.audience,sceneTitle:s.title,step:String(n+1).padStart(2,'0')+' / '+String(v.scenes.length).padStart(2,'0')};const file=path.join(assets,s.id+'.png');const key=hash([source,'frame-v2',inputProps]);if(!await valid(file,key))jobs.push({id:'Frame',inputProps,file,key});}}
if(!jobs.length){console.log('All selected Remotion assets are cached.');process.exit(0)}
const serveUrl=await bundle({entryPoint:path.join(here,'Composition.tsx'),outDir:path.join(run,'remotion-bundle')});
for(const {id,inputProps,file,key} of jobs){const composition=await selectComposition({serveUrl,id,inputProps});if(id==='Title')await renderMedia({serveUrl,composition,inputProps,codec:'h264',outputLocation:file,concurrency:2,crf:20,logLevel:'warn'});else await renderStill({serveUrl,composition,inputProps,output:file,imageFormat:'png',logLevel:'warn'});await fs.writeFile(file+'.sha256',key);console.log('Remotion asset ready '+path.basename(file));}
